
package br.com.supermercado.telas;

import br.com.supermercado.dal.ModuloDeConexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Paulo Abreu
 */
public class TelaVendas extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
        
                URL caminhoIconeTelaPrincipal = getClass().getResource("/br/com/supermercado/icones/OS_LogoMarca.png");
Image iconeTelaPrincipal = Toolkit.getDefaultToolkit().getImage(  caminhoIconeTelaPrincipal);
this.setIconImage(iconeTelaPrincipal);

        conexao = ModuloDeConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTelaVendasVendas = new javax.swing.JPanel();
        jlTelaVendasDescricao = new javax.swing.JLabel();
        jlTelaVendasQuantidade = new javax.swing.JLabel();
        jlTelaVendasValor = new javax.swing.JLabel();
        jtfTelaVandasDescricao = new javax.swing.JTextField();
        jtfTelaVendasQuantidade = new javax.swing.JTextField();
        jtfTelaVendasValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlTelaVendasVendasTotal = new javax.swing.JLabel();
        jlTelaVendasValorValorTotal = new javax.swing.JLabel();
        jlTelaVendasVendasSubTotal = new javax.swing.JLabel();
        jtfValorTotal = new javax.swing.JTextField();
        jtfTelaVendasValorValor = new javax.swing.JTextField();
        jtfTelaVendasSusTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTelaVendasImagemFundoGrafite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado - Vendas");
        setExtendedState(6);
        getContentPane().setLayout(null);

        jpTelaVendasVendas.setBackground(new java.awt.Color(255, 0, 0));
        jpTelaVendasVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 36))); // NOI18N
        jpTelaVendasVendas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jpTelaVendasVendas.setLayout(null);

        jlTelaVendasDescricao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasDescricao.setText("Descriçao");
        jpTelaVendasVendas.add(jlTelaVendasDescricao);
        jlTelaVendasDescricao.setBounds(50, 70, 130, 30);

        jlTelaVendasQuantidade.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasQuantidade.setText("Quantidade");
        jpTelaVendasVendas.add(jlTelaVendasQuantidade);
        jlTelaVendasQuantidade.setBounds(750, 70, 140, 30);

        jlTelaVendasValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasValor.setText("Valor");
        jpTelaVendasVendas.add(jlTelaVendasValor);
        jlTelaVendasValor.setBounds(1040, 70, 70, 30);
        jpTelaVendasVendas.add(jtfTelaVandasDescricao);
        jtfTelaVandasDescricao.setBounds(170, 70, 570, 40);
        jpTelaVendasVendas.add(jtfTelaVendasQuantidade);
        jtfTelaVendasQuantidade.setBounds(890, 70, 140, 40);
        jpTelaVendasVendas.add(jtfTelaVendasValor);
        jtfTelaVendasValor.setBounds(1110, 70, 190, 40);

        getContentPane().add(jpTelaVendasVendas);
        jpTelaVendasVendas.setBounds(20, 120, 1330, 170);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Valor ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 36))); // NOI18N
        jPanel1.setLayout(null);

        jlTelaVendasVendasTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasVendasTotal.setText("Total");
        jPanel1.add(jlTelaVendasVendasTotal);
        jlTelaVendasVendasTotal.setBounds(50, 80, 70, 30);

        jlTelaVendasValorValorTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasValorValorTotal.setText("Valor Total");
        jPanel1.add(jlTelaVendasValorValorTotal);
        jlTelaVendasValorValorTotal.setBounds(50, 140, 140, 30);

        jlTelaVendasVendasSubTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlTelaVendasVendasSubTotal.setText("SubTotal");
        jPanel1.add(jlTelaVendasVendasSubTotal);
        jlTelaVendasVendasSubTotal.setBounds(50, 200, 120, 30);
        jPanel1.add(jtfValorTotal);
        jtfValorTotal.setBounds(200, 130, 230, 40);
        jPanel1.add(jtfTelaVendasValorValor);
        jtfTelaVendasValorValor.setBounds(200, 70, 230, 40);
        jPanel1.add(jtfTelaVendasSusTotal);
        jtfTelaVendasSusTotal.setBounds(200, 190, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 330, 470, 280);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Caixa");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 20, 60, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Data");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(260, 20, 60, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Hora");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(460, 20, 60, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(690, 30, 660, 60);

        jlTelaVendasImagemFundoGrafite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/supermercado/icones/imagemGrafiteTelaFundoJPcadastroUsuarioMenu.jpg"))); // NOI18N
        getContentPane().add(jlTelaVendasImagemFundoGrafite);
        jlTelaVendasImagemFundoGrafite.setBounds(0, 0, 1370, 720);

        setSize(new java.awt.Dimension(1386, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlTelaVendasDescricao;
    private javax.swing.JLabel jlTelaVendasImagemFundoGrafite;
    private javax.swing.JLabel jlTelaVendasQuantidade;
    private javax.swing.JLabel jlTelaVendasValor;
    private javax.swing.JLabel jlTelaVendasValorValorTotal;
    private javax.swing.JLabel jlTelaVendasVendasSubTotal;
    private javax.swing.JLabel jlTelaVendasVendasTotal;
    private javax.swing.JPanel jpTelaVendasVendas;
    private javax.swing.JTextField jtfTelaVandasDescricao;
    private javax.swing.JTextField jtfTelaVendasQuantidade;
    private javax.swing.JTextField jtfTelaVendasSusTotal;
    private javax.swing.JTextField jtfTelaVendasValor;
    private javax.swing.JTextField jtfTelaVendasValorValor;
    private javax.swing.JTextField jtfValorTotal;
    // End of variables declaration//GEN-END:variables
}
