package br.com.supermercado.telas;

import br.com.supermercado.dal.ModuloDeConexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author Paulo Abreu
 */
public class TelaPrincipal extends javax.swing.JFrame {
 Connection conexao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        initComponents();
        
        URL caminhoIconeTelaPrincipal = getClass().getResource("/br/com/supermercado/icones/OS_LogoMarca.png");
Image iconeTelaPrincipal = Toolkit.getDefaultToolkit().getImage(  caminhoIconeTelaPrincipal);
this.setIconImage(iconeTelaPrincipal);

        conexao = ModuloDeConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlTelaFundoPrincipal = new javax.swing.JLabel();
        jmbTelaPrincipalMenu = new javax.swing.JMenuBar();
        jmTelaPrincipalMenuMenuCadastros = new javax.swing.JMenu();
        jmTelaPrincipalMenuMenuUsuario = new javax.swing.JMenuItem();
        jmTelaPrincipaMenuMenulFornecedores = new javax.swing.JMenuItem();
        jmTelaPrincipalMenuMenuProdutos = new javax.swing.JMenuItem();
        jmTelaPrincipalMenuMenuVendas = new javax.swing.JMenu();
        jmTelaPrincipalMenuVendasCaixa = new javax.swing.JMenuItem();
        jmTelaPrincipalMenuMenuPedidos = new javax.swing.JMenu();
        jmTelaPrincipalMenuPedidosNovo = new javax.swing.JMenuItem();
        jmTelaPrincipalMenuMenuFerramentas = new javax.swing.JMenu();
        jmTelaPrincipalMenuMenuRelatorios = new javax.swing.JMenu();
        jmTelaPrincipalMenuMenuSair = new javax.swing.JMenu();
        jmTelaPrincipalMenuSairSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado - Tela Principal");
        setExtendedState(6);
        setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Tela Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/supermercado/icones/imagemLogoCarroSupermercado01.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 170, 390, 410);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Supermercado Sergipe");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 70, 570, 90);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Preços mais baixos ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 300, 360, 43);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("não existe");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 360, 190, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 50, 820, 590);

        jlTelaFundoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jlTelaFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/supermercado/icones/imagemGrafiteTelaFundoJPcadastroUsuarioMenu.jpg"))); // NOI18N
        getContentPane().add(jlTelaFundoPrincipal);
        jlTelaFundoPrincipal.setBounds(0, 0, 1370, 710);

        jmTelaPrincipalMenuMenuCadastros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jmTelaPrincipalMenuMenuCadastros.setText("Cadastros");
        jmTelaPrincipalMenuMenuCadastros.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmTelaPrincipalMenuMenuUsuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuMenuUsuario.setText("Usuários");
        jmTelaPrincipalMenuMenuUsuario.setEnabled(false);
        jmTelaPrincipalMenuMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaPrincipalMenuMenuUsuarioActionPerformed(evt);
            }
        });
        jmTelaPrincipalMenuMenuCadastros.add(jmTelaPrincipalMenuMenuUsuario);

        jmTelaPrincipaMenuMenulFornecedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipaMenuMenulFornecedores.setText("Fornecedores");
        jmTelaPrincipaMenuMenulFornecedores.setEnabled(false);
        jmTelaPrincipalMenuMenuCadastros.add(jmTelaPrincipaMenuMenulFornecedores);

        jmTelaPrincipalMenuMenuProdutos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuMenuProdutos.setText("Produtos");
        jmTelaPrincipalMenuMenuProdutos.setEnabled(false);
        jmTelaPrincipalMenuMenuCadastros.add(jmTelaPrincipalMenuMenuProdutos);

        jmbTelaPrincipalMenu.add(jmTelaPrincipalMenuMenuCadastros);

        jmTelaPrincipalMenuMenuVendas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jmTelaPrincipalMenuMenuVendas.setText("Vendas");
        jmTelaPrincipalMenuMenuVendas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmTelaPrincipalMenuVendasCaixa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuVendasCaixa.setText("Caixa");
        jmTelaPrincipalMenuVendasCaixa.setEnabled(false);
        jmTelaPrincipalMenuVendasCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaPrincipalMenuVendasCaixaActionPerformed(evt);
            }
        });
        jmTelaPrincipalMenuMenuVendas.add(jmTelaPrincipalMenuVendasCaixa);

        jmbTelaPrincipalMenu.add(jmTelaPrincipalMenuMenuVendas);

        jmTelaPrincipalMenuMenuPedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jmTelaPrincipalMenuMenuPedidos.setText("Pedidos");
        jmTelaPrincipalMenuMenuPedidos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmTelaPrincipalMenuPedidosNovo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuPedidosNovo.setText("Novo");
        jmTelaPrincipalMenuPedidosNovo.setEnabled(false);
        jmTelaPrincipalMenuMenuPedidos.add(jmTelaPrincipalMenuPedidosNovo);

        jmbTelaPrincipalMenu.add(jmTelaPrincipalMenuMenuPedidos);

        jmTelaPrincipalMenuMenuFerramentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jmTelaPrincipalMenuMenuFerramentas.setText("Ferramentas");
        jmTelaPrincipalMenuMenuFerramentas.setEnabled(false);
        jmTelaPrincipalMenuMenuFerramentas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmTelaPrincipalMenuMenuRelatorios.setBorder(null);
        jmTelaPrincipalMenuMenuRelatorios.setText("Relatórios");
        jmTelaPrincipalMenuMenuRelatorios.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuMenuFerramentas.add(jmTelaPrincipalMenuMenuRelatorios);

        jmbTelaPrincipalMenu.add(jmTelaPrincipalMenuMenuFerramentas);

        jmTelaPrincipalMenuMenuSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jmTelaPrincipalMenuMenuSair.setText("Sair");
        jmTelaPrincipalMenuMenuSair.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jmTelaPrincipalMenuMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaPrincipalMenuMenuSairActionPerformed(evt);
            }
        });

        jmTelaPrincipalMenuSairSair.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jmTelaPrincipalMenuSairSair.setText("Sair");
        jmTelaPrincipalMenuSairSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaPrincipalMenuSairSairActionPerformed(evt);
            }
        });
        jmTelaPrincipalMenuMenuSair.add(jmTelaPrincipalMenuSairSair);

        jmbTelaPrincipalMenu.add(jmTelaPrincipalMenuMenuSair);

        setJMenuBar(jmbTelaPrincipalMenu);

        setSize(new java.awt.Dimension(1385, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmTelaPrincipalMenuMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaPrincipalMenuMenuUsuarioActionPerformed
        
        TelaCadastroUsuarios tcu = new TelaCadastroUsuarios();
        tcu.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jmTelaPrincipalMenuMenuUsuarioActionPerformed

    private void jmTelaPrincipalMenuMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaPrincipalMenuMenuSairActionPerformed

    }//GEN-LAST:event_jmTelaPrincipalMenuMenuSairActionPerformed

    private void jmTelaPrincipalMenuSairSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaPrincipalMenuSairSairActionPerformed
                     int sair  = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION );
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jmTelaPrincipalMenuSairSairActionPerformed

    private void jmTelaPrincipalMenuVendasCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaPrincipalMenuVendasCaixaActionPerformed
       TelaVendas tv = new TelaVendas();
       tv.setVisible(true);
       
    }//GEN-LAST:event_jmTelaPrincipalMenuVendasCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlTelaFundoPrincipal;
    public static javax.swing.JMenuItem jmTelaPrincipaMenuMenulFornecedores;
    private javax.swing.JMenu jmTelaPrincipalMenuMenuCadastros;
    public static javax.swing.JMenu jmTelaPrincipalMenuMenuFerramentas;
    private javax.swing.JMenu jmTelaPrincipalMenuMenuPedidos;
    public static javax.swing.JMenuItem jmTelaPrincipalMenuMenuProdutos;
    private javax.swing.JMenu jmTelaPrincipalMenuMenuRelatorios;
    private javax.swing.JMenu jmTelaPrincipalMenuMenuSair;
    public static javax.swing.JMenuItem jmTelaPrincipalMenuMenuUsuario;
    private javax.swing.JMenu jmTelaPrincipalMenuMenuVendas;
    public static javax.swing.JMenuItem jmTelaPrincipalMenuPedidosNovo;
    private javax.swing.JMenuItem jmTelaPrincipalMenuSairSair;
    public static javax.swing.JMenuItem jmTelaPrincipalMenuVendasCaixa;
    private javax.swing.JMenuBar jmbTelaPrincipalMenu;
    // End of variables declaration//GEN-END:variables
}
